//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.WSDesmaterializado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sio.experian.com/", ConfigurationName="WSDesmaterializado.SIOType")]
    public interface SIOType {
        
        // CODEGEN: Generating message contract since the wrapper name (Request) of message WSDesmaterializadoRequest does not match the default value (WSDesmaterializado)
        [System.ServiceModel.OperationContractAttribute(Action="WSDesmaterializado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication.WSDesmaterializado.WSDesmaterializadoResponse WSDesmaterializado(WebApplication.WSDesmaterializado.WSDesmaterializadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSDesmaterializado", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.WSDesmaterializado.WSDesmaterializadoResponse> WSDesmaterializadoAsync(WebApplication.WSDesmaterializado.WSDesmaterializadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class RequestWSDesmaterializadoReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroSolicitudField;
        
        private long numeroIDField;
        
        private long tipoIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroSolicitud {
            get {
                return this.numeroSolicitudField;
            }
            set {
                this.numeroSolicitudField = value;
                this.RaisePropertyChanged("NumeroSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long NumeroID {
            get {
                return this.numeroIDField;
            }
            set {
                this.numeroIDField = value;
                this.RaisePropertyChanged("NumeroID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long TipoID {
            get {
                return this.tipoIDField;
            }
            set {
                this.tipoIDField = value;
                this.RaisePropertyChanged("TipoID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long respuestaField;
        
        private bool respuestaFieldSpecified;
        
        private ResponseWSDesmaterializadoRespSolicitud solicitudField;
        
        private ResponseWSDesmaterializadoRespCliente[] clienteField;
        
        private ResponseWSDesmaterializadoRespMasivas masivasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool respuestaSpecified {
            get {
                return this.respuestaFieldSpecified;
            }
            set {
                this.respuestaFieldSpecified = value;
                this.RaisePropertyChanged("respuestaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseWSDesmaterializadoRespSolicitud Solicitud {
            get {
                return this.solicitudField;
            }
            set {
                this.solicitudField = value;
                this.RaisePropertyChanged("Solicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cliente", Order=2)]
        public ResponseWSDesmaterializadoRespCliente[] Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResponseWSDesmaterializadoRespMasivas Masivas {
            get {
                return this.masivasField;
            }
            set {
                this.masivasField = value;
                this.RaisePropertyChanged("Masivas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespSolicitud : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string solicitudIdField;
        
        private string ciudadDiligenciamientoField;
        
        private string fechaCreacionField;
        
        private string fechaUltActualizacionField;
        
        private string fechaConsultaField;
        
        private string alianzaField;
        
        private string almacenField;
        
        private string codigoAsesorField;
        
        private string lineaFinanciacionField;
        
        private decimal cuotaManejoField;
        
        private bool cuotaManejoFieldSpecified;
        
        private decimal valorComercialField;
        
        private bool valorComercialFieldSpecified;
        
        private string cattEntregaField;
        
        private string ciudadEntregaDomiciliosDescField;
        
        private string direccionEntregaMCConsolidadoField;
        
        private decimal valorSolicitadoField;
        
        private bool valorSolicitadoFieldSpecified;
        
        private decimal valorAprobadoField;
        
        private bool valorAprobadoFieldSpecified;
        
        private long diaPagoField;
        
        private bool diaPagoFieldSpecified;
        
        private string modalidadPagoField;
        
        private long plazoCredicomprasField;
        
        private bool plazoCredicomprasFieldSpecified;
        
        private long plazoMotosField;
        
        private bool plazoMotosFieldSpecified;
        
        private decimal tasaEASimuladorField;
        
        private bool tasaEASimuladorFieldSpecified;
        
        private decimal polizaDeudoresField;
        
        private bool polizaDeudoresFieldSpecified;
        
        private decimal cuotaCrediCompraField;
        
        private bool cuotaCrediCompraFieldSpecified;
        
        private string pagareField;
        
        private long estadoIDField;
        
        private bool estadoIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SolicitudId {
            get {
                return this.solicitudIdField;
            }
            set {
                this.solicitudIdField = value;
                this.RaisePropertyChanged("SolicitudId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CiudadDiligenciamiento {
            get {
                return this.ciudadDiligenciamientoField;
            }
            set {
                this.ciudadDiligenciamientoField = value;
                this.RaisePropertyChanged("CiudadDiligenciamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FechaUltActualizacion {
            get {
                return this.fechaUltActualizacionField;
            }
            set {
                this.fechaUltActualizacionField = value;
                this.RaisePropertyChanged("FechaUltActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FechaConsulta {
            get {
                return this.fechaConsultaField;
            }
            set {
                this.fechaConsultaField = value;
                this.RaisePropertyChanged("FechaConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Alianza {
            get {
                return this.alianzaField;
            }
            set {
                this.alianzaField = value;
                this.RaisePropertyChanged("Alianza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Almacen {
            get {
                return this.almacenField;
            }
            set {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CodigoAsesor {
            get {
                return this.codigoAsesorField;
            }
            set {
                this.codigoAsesorField = value;
                this.RaisePropertyChanged("CodigoAsesor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LineaFinanciacion {
            get {
                return this.lineaFinanciacionField;
            }
            set {
                this.lineaFinanciacionField = value;
                this.RaisePropertyChanged("LineaFinanciacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal CuotaManejo {
            get {
                return this.cuotaManejoField;
            }
            set {
                this.cuotaManejoField = value;
                this.RaisePropertyChanged("CuotaManejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CuotaManejoSpecified {
            get {
                return this.cuotaManejoFieldSpecified;
            }
            set {
                this.cuotaManejoFieldSpecified = value;
                this.RaisePropertyChanged("CuotaManejoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal ValorComercial {
            get {
                return this.valorComercialField;
            }
            set {
                this.valorComercialField = value;
                this.RaisePropertyChanged("ValorComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorComercialSpecified {
            get {
                return this.valorComercialFieldSpecified;
            }
            set {
                this.valorComercialFieldSpecified = value;
                this.RaisePropertyChanged("ValorComercialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CattEntrega {
            get {
                return this.cattEntregaField;
            }
            set {
                this.cattEntregaField = value;
                this.RaisePropertyChanged("CattEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CiudadEntregaDomiciliosDesc {
            get {
                return this.ciudadEntregaDomiciliosDescField;
            }
            set {
                this.ciudadEntregaDomiciliosDescField = value;
                this.RaisePropertyChanged("CiudadEntregaDomiciliosDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DireccionEntregaMCConsolidado {
            get {
                return this.direccionEntregaMCConsolidadoField;
            }
            set {
                this.direccionEntregaMCConsolidadoField = value;
                this.RaisePropertyChanged("DireccionEntregaMCConsolidado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal ValorSolicitado {
            get {
                return this.valorSolicitadoField;
            }
            set {
                this.valorSolicitadoField = value;
                this.RaisePropertyChanged("ValorSolicitado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorSolicitadoSpecified {
            get {
                return this.valorSolicitadoFieldSpecified;
            }
            set {
                this.valorSolicitadoFieldSpecified = value;
                this.RaisePropertyChanged("ValorSolicitadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal ValorAprobado {
            get {
                return this.valorAprobadoField;
            }
            set {
                this.valorAprobadoField = value;
                this.RaisePropertyChanged("ValorAprobado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorAprobadoSpecified {
            get {
                return this.valorAprobadoFieldSpecified;
            }
            set {
                this.valorAprobadoFieldSpecified = value;
                this.RaisePropertyChanged("ValorAprobadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long DiaPago {
            get {
                return this.diaPagoField;
            }
            set {
                this.diaPagoField = value;
                this.RaisePropertyChanged("DiaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiaPagoSpecified {
            get {
                return this.diaPagoFieldSpecified;
            }
            set {
                this.diaPagoFieldSpecified = value;
                this.RaisePropertyChanged("DiaPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ModalidadPago {
            get {
                return this.modalidadPagoField;
            }
            set {
                this.modalidadPagoField = value;
                this.RaisePropertyChanged("ModalidadPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long PlazoCredicompras {
            get {
                return this.plazoCredicomprasField;
            }
            set {
                this.plazoCredicomprasField = value;
                this.RaisePropertyChanged("PlazoCredicompras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlazoCredicomprasSpecified {
            get {
                return this.plazoCredicomprasFieldSpecified;
            }
            set {
                this.plazoCredicomprasFieldSpecified = value;
                this.RaisePropertyChanged("PlazoCredicomprasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public long PlazoMotos {
            get {
                return this.plazoMotosField;
            }
            set {
                this.plazoMotosField = value;
                this.RaisePropertyChanged("PlazoMotos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlazoMotosSpecified {
            get {
                return this.plazoMotosFieldSpecified;
            }
            set {
                this.plazoMotosFieldSpecified = value;
                this.RaisePropertyChanged("PlazoMotosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal TasaEASimulador {
            get {
                return this.tasaEASimuladorField;
            }
            set {
                this.tasaEASimuladorField = value;
                this.RaisePropertyChanged("TasaEASimulador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TasaEASimuladorSpecified {
            get {
                return this.tasaEASimuladorFieldSpecified;
            }
            set {
                this.tasaEASimuladorFieldSpecified = value;
                this.RaisePropertyChanged("TasaEASimuladorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal PolizaDeudores {
            get {
                return this.polizaDeudoresField;
            }
            set {
                this.polizaDeudoresField = value;
                this.RaisePropertyChanged("PolizaDeudores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolizaDeudoresSpecified {
            get {
                return this.polizaDeudoresFieldSpecified;
            }
            set {
                this.polizaDeudoresFieldSpecified = value;
                this.RaisePropertyChanged("PolizaDeudoresSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal CuotaCrediCompra {
            get {
                return this.cuotaCrediCompraField;
            }
            set {
                this.cuotaCrediCompraField = value;
                this.RaisePropertyChanged("CuotaCrediCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CuotaCrediCompraSpecified {
            get {
                return this.cuotaCrediCompraFieldSpecified;
            }
            set {
                this.cuotaCrediCompraFieldSpecified = value;
                this.RaisePropertyChanged("CuotaCrediCompraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Pagare {
            get {
                return this.pagareField;
            }
            set {
                this.pagareField = value;
                this.RaisePropertyChanged("Pagare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public long EstadoID {
            get {
                return this.estadoIDField;
            }
            set {
                this.estadoIDField = value;
                this.RaisePropertyChanged("EstadoID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoIDSpecified {
            get {
                return this.estadoIDFieldSpecified;
            }
            set {
                this.estadoIDFieldSpecified = value;
                this.RaisePropertyChanged("EstadoIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string primerNombreField;
        
        private string segundoNombreField;
        
        private long tipoIDField;
        
        private bool tipoIDFieldSpecified;
        
        private decimal numeroIDField;
        
        private bool numeroIDFieldSpecified;
        
        private string fechaExpedicionCedulaField;
        
        private string fechaNacimientoField;
        
        private string lugarNacimientoField;
        
        private long generoField;
        
        private bool generoFieldSpecified;
        
        private long personasCargoField;
        
        private bool personasCargoFieldSpecified;
        
        private long hijosConvivientesField;
        
        private bool hijosConvivientesFieldSpecified;
        
        private long estadoCivilField;
        
        private bool estadoCivilFieldSpecified;
        
        private string tipoViviendaField;
        
        private long tiempoViviendaField;
        
        private bool tiempoViviendaFieldSpecified;
        
        private long estratoField;
        
        private bool estratoFieldSpecified;
        
        private long estudiosRealizadosField;
        
        private bool estudiosRealizadosFieldSpecified;
        
        private string barrioField;
        
        private string direccionResidenciaConsolidadoField;
        
        private string ciudadResidenciaDescField;
        
        private string departamentoField;
        
        private long paisResidenciaField;
        
        private bool paisResidenciaFieldSpecified;
        
        private decimal telefonoResidenciaField;
        
        private bool telefonoResidenciaFieldSpecified;
        
        private long envioCorrespondenciaField;
        
        private bool envioCorrespondenciaFieldSpecified;
        
        private string emailField;
        
        private decimal celularField;
        
        private bool celularFieldSpecified;
        
        private long oficioOProfesionField;
        
        private bool oficioOProfesionFieldSpecified;
        
        private ResponseWSDesmaterializadoRespClienteLaboral laboralField;
        
        private ResponseWSDesmaterializadoRespClienteFinanciero financieroField;
        
        private ResponseWSDesmaterializadoRespClienteSarlaft sarlaftField;
        
        private ResponseWSDesmaterializadoRespClienteRef refField;
        
        private ResponseWSDesmaterializadoRespClienteActivos activosField;
        
        private string clientePepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("PrimerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("SegundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrimerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
                this.RaisePropertyChanged("PrimerNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
                this.RaisePropertyChanged("SegundoNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long TipoID {
            get {
                return this.tipoIDField;
            }
            set {
                this.tipoIDField = value;
                this.RaisePropertyChanged("TipoID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoIDSpecified {
            get {
                return this.tipoIDFieldSpecified;
            }
            set {
                this.tipoIDFieldSpecified = value;
                this.RaisePropertyChanged("TipoIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal NumeroID {
            get {
                return this.numeroIDField;
            }
            set {
                this.numeroIDField = value;
                this.RaisePropertyChanged("NumeroID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroIDSpecified {
            get {
                return this.numeroIDFieldSpecified;
            }
            set {
                this.numeroIDFieldSpecified = value;
                this.RaisePropertyChanged("NumeroIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FechaExpedicionCedula {
            get {
                return this.fechaExpedicionCedulaField;
            }
            set {
                this.fechaExpedicionCedulaField = value;
                this.RaisePropertyChanged("FechaExpedicionCedula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("FechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LugarNacimiento {
            get {
                return this.lugarNacimientoField;
            }
            set {
                this.lugarNacimientoField = value;
                this.RaisePropertyChanged("LugarNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long Genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("Genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeneroSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("GeneroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long PersonasCargo {
            get {
                return this.personasCargoField;
            }
            set {
                this.personasCargoField = value;
                this.RaisePropertyChanged("PersonasCargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonasCargoSpecified {
            get {
                return this.personasCargoFieldSpecified;
            }
            set {
                this.personasCargoFieldSpecified = value;
                this.RaisePropertyChanged("PersonasCargoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long HijosConvivientes {
            get {
                return this.hijosConvivientesField;
            }
            set {
                this.hijosConvivientesField = value;
                this.RaisePropertyChanged("HijosConvivientes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HijosConvivientesSpecified {
            get {
                return this.hijosConvivientesFieldSpecified;
            }
            set {
                this.hijosConvivientesFieldSpecified = value;
                this.RaisePropertyChanged("HijosConvivientesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("EstadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoCivilSpecified {
            get {
                return this.estadoCivilFieldSpecified;
            }
            set {
                this.estadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("EstadoCivilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TipoVivienda {
            get {
                return this.tipoViviendaField;
            }
            set {
                this.tipoViviendaField = value;
                this.RaisePropertyChanged("TipoVivienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long TiempoVivienda {
            get {
                return this.tiempoViviendaField;
            }
            set {
                this.tiempoViviendaField = value;
                this.RaisePropertyChanged("TiempoVivienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TiempoViviendaSpecified {
            get {
                return this.tiempoViviendaFieldSpecified;
            }
            set {
                this.tiempoViviendaFieldSpecified = value;
                this.RaisePropertyChanged("TiempoViviendaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long Estrato {
            get {
                return this.estratoField;
            }
            set {
                this.estratoField = value;
                this.RaisePropertyChanged("Estrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstratoSpecified {
            get {
                return this.estratoFieldSpecified;
            }
            set {
                this.estratoFieldSpecified = value;
                this.RaisePropertyChanged("EstratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long EstudiosRealizados {
            get {
                return this.estudiosRealizadosField;
            }
            set {
                this.estudiosRealizadosField = value;
                this.RaisePropertyChanged("EstudiosRealizados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstudiosRealizadosSpecified {
            get {
                return this.estudiosRealizadosFieldSpecified;
            }
            set {
                this.estudiosRealizadosFieldSpecified = value;
                this.RaisePropertyChanged("EstudiosRealizadosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Barrio {
            get {
                return this.barrioField;
            }
            set {
                this.barrioField = value;
                this.RaisePropertyChanged("Barrio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DireccionResidenciaConsolidado {
            get {
                return this.direccionResidenciaConsolidadoField;
            }
            set {
                this.direccionResidenciaConsolidadoField = value;
                this.RaisePropertyChanged("DireccionResidenciaConsolidado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CiudadResidenciaDesc {
            get {
                return this.ciudadResidenciaDescField;
            }
            set {
                this.ciudadResidenciaDescField = value;
                this.RaisePropertyChanged("CiudadResidenciaDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("Departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public long PaisResidencia {
            get {
                return this.paisResidenciaField;
            }
            set {
                this.paisResidenciaField = value;
                this.RaisePropertyChanged("PaisResidencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaisResidenciaSpecified {
            get {
                return this.paisResidenciaFieldSpecified;
            }
            set {
                this.paisResidenciaFieldSpecified = value;
                this.RaisePropertyChanged("PaisResidenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal TelefonoResidencia {
            get {
                return this.telefonoResidenciaField;
            }
            set {
                this.telefonoResidenciaField = value;
                this.RaisePropertyChanged("TelefonoResidencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelefonoResidenciaSpecified {
            get {
                return this.telefonoResidenciaFieldSpecified;
            }
            set {
                this.telefonoResidenciaFieldSpecified = value;
                this.RaisePropertyChanged("TelefonoResidenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public long EnvioCorrespondencia {
            get {
                return this.envioCorrespondenciaField;
            }
            set {
                this.envioCorrespondenciaField = value;
                this.RaisePropertyChanged("EnvioCorrespondencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnvioCorrespondenciaSpecified {
            get {
                return this.envioCorrespondenciaFieldSpecified;
            }
            set {
                this.envioCorrespondenciaFieldSpecified = value;
                this.RaisePropertyChanged("EnvioCorrespondenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CelularSpecified {
            get {
                return this.celularFieldSpecified;
            }
            set {
                this.celularFieldSpecified = value;
                this.RaisePropertyChanged("CelularSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public long OficioOProfesion {
            get {
                return this.oficioOProfesionField;
            }
            set {
                this.oficioOProfesionField = value;
                this.RaisePropertyChanged("OficioOProfesion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OficioOProfesionSpecified {
            get {
                return this.oficioOProfesionFieldSpecified;
            }
            set {
                this.oficioOProfesionFieldSpecified = value;
                this.RaisePropertyChanged("OficioOProfesionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public ResponseWSDesmaterializadoRespClienteLaboral Laboral {
            get {
                return this.laboralField;
            }
            set {
                this.laboralField = value;
                this.RaisePropertyChanged("Laboral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public ResponseWSDesmaterializadoRespClienteFinanciero Financiero {
            get {
                return this.financieroField;
            }
            set {
                this.financieroField = value;
                this.RaisePropertyChanged("Financiero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public ResponseWSDesmaterializadoRespClienteSarlaft Sarlaft {
            get {
                return this.sarlaftField;
            }
            set {
                this.sarlaftField = value;
                this.RaisePropertyChanged("Sarlaft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public ResponseWSDesmaterializadoRespClienteRef Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("Ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public ResponseWSDesmaterializadoRespClienteActivos Activos {
            get {
                return this.activosField;
            }
            set {
                this.activosField = value;
                this.RaisePropertyChanged("Activos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ClientePep {
            get {
                return this.clientePepField;
            }
            set {
                this.clientePepField = value;
                this.RaisePropertyChanged("ClientePep");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteLaboral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long ocupacionField;
        
        private bool ocupacionFieldSpecified;
        
        private long tipoContratoField;
        
        private bool tipoContratoFieldSpecified;
        
        private string otroTipoContratoField;
        
        private string nombreEmpresaField;
        
        private long cargoActividadField;
        
        private bool cargoActividadFieldSpecified;
        
        private string direccionEmpresaConsolidadoField;
        
        private long tiempoEmpresaField;
        
        private bool tiempoEmpresaFieldSpecified;
        
        private decimal telefonoField;
        
        private bool telefonoFieldSpecified;
        
        private string ciudadDescField;
        
        private long tipoDeActividadField;
        
        private bool tipoDeActividadFieldSpecified;
        
        private long tiempoActividadField;
        
        private bool tiempoActividadFieldSpecified;
        
        private long actividadEcPrincipalField;
        
        private bool actividadEcPrincipalFieldSpecified;
        
        private string funcionPublicaField;
        
        private long vinculoPublicoField;
        
        private bool vinculoPublicoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
                this.RaisePropertyChanged("Ocupacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OcupacionSpecified {
            get {
                return this.ocupacionFieldSpecified;
            }
            set {
                this.ocupacionFieldSpecified = value;
                this.RaisePropertyChanged("OcupacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TipoContrato {
            get {
                return this.tipoContratoField;
            }
            set {
                this.tipoContratoField = value;
                this.RaisePropertyChanged("TipoContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoContratoSpecified {
            get {
                return this.tipoContratoFieldSpecified;
            }
            set {
                this.tipoContratoFieldSpecified = value;
                this.RaisePropertyChanged("TipoContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OtroTipoContrato {
            get {
                return this.otroTipoContratoField;
            }
            set {
                this.otroTipoContratoField = value;
                this.RaisePropertyChanged("OtroTipoContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                this.nombreEmpresaField = value;
                this.RaisePropertyChanged("NombreEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long CargoActividad {
            get {
                return this.cargoActividadField;
            }
            set {
                this.cargoActividadField = value;
                this.RaisePropertyChanged("CargoActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CargoActividadSpecified {
            get {
                return this.cargoActividadFieldSpecified;
            }
            set {
                this.cargoActividadFieldSpecified = value;
                this.RaisePropertyChanged("CargoActividadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DireccionEmpresaConsolidado {
            get {
                return this.direccionEmpresaConsolidadoField;
            }
            set {
                this.direccionEmpresaConsolidadoField = value;
                this.RaisePropertyChanged("DireccionEmpresaConsolidado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long TiempoEmpresa {
            get {
                return this.tiempoEmpresaField;
            }
            set {
                this.tiempoEmpresaField = value;
                this.RaisePropertyChanged("TiempoEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TiempoEmpresaSpecified {
            get {
                return this.tiempoEmpresaFieldSpecified;
            }
            set {
                this.tiempoEmpresaFieldSpecified = value;
                this.RaisePropertyChanged("TiempoEmpresaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("TelefonoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CiudadDesc {
            get {
                return this.ciudadDescField;
            }
            set {
                this.ciudadDescField = value;
                this.RaisePropertyChanged("CiudadDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long TipoDeActividad {
            get {
                return this.tipoDeActividadField;
            }
            set {
                this.tipoDeActividadField = value;
                this.RaisePropertyChanged("TipoDeActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoDeActividadSpecified {
            get {
                return this.tipoDeActividadFieldSpecified;
            }
            set {
                this.tipoDeActividadFieldSpecified = value;
                this.RaisePropertyChanged("TipoDeActividadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long TiempoActividad {
            get {
                return this.tiempoActividadField;
            }
            set {
                this.tiempoActividadField = value;
                this.RaisePropertyChanged("TiempoActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TiempoActividadSpecified {
            get {
                return this.tiempoActividadFieldSpecified;
            }
            set {
                this.tiempoActividadFieldSpecified = value;
                this.RaisePropertyChanged("TiempoActividadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long ActividadEcPrincipal {
            get {
                return this.actividadEcPrincipalField;
            }
            set {
                this.actividadEcPrincipalField = value;
                this.RaisePropertyChanged("ActividadEcPrincipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActividadEcPrincipalSpecified {
            get {
                return this.actividadEcPrincipalFieldSpecified;
            }
            set {
                this.actividadEcPrincipalFieldSpecified = value;
                this.RaisePropertyChanged("ActividadEcPrincipalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FuncionPublica {
            get {
                return this.funcionPublicaField;
            }
            set {
                this.funcionPublicaField = value;
                this.RaisePropertyChanged("FuncionPublica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long VinculoPublico {
            get {
                return this.vinculoPublicoField;
            }
            set {
                this.vinculoPublicoField = value;
                this.RaisePropertyChanged("VinculoPublico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VinculoPublicoSpecified {
            get {
                return this.vinculoPublicoFieldSpecified;
            }
            set {
                this.vinculoPublicoFieldSpecified = value;
                this.RaisePropertyChanged("VinculoPublicoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteFinanciero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal ingresosAcPrincipalField;
        
        private bool ingresosAcPrincipalFieldSpecified;
        
        private decimal otrosIngresosField;
        
        private bool otrosIngresosFieldSpecified;
        
        private decimal totalIngresosField;
        
        private bool totalIngresosFieldSpecified;
        
        private decimal totalActivosField;
        
        private bool totalActivosFieldSpecified;
        
        private decimal totalPasivosField;
        
        private bool totalPasivosFieldSpecified;
        
        private decimal gastosTotalesField;
        
        private bool gastosTotalesFieldSpecified;
        
        private string opMonedaExtranjeraField;
        
        private long tipoOperacionMEField;
        
        private bool tipoOperacionMEFieldSpecified;
        
        private string entidadOPMEField;
        
        private string otraOperacionMEField;
        
        private string ciudadField;
        
        private long tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        private decimal montoField;
        
        private bool montoFieldSpecified;
        
        private string otroTipoDeProductoField;
        
        private string monedaField;
        
        private string cuentaBancariaField;
        
        private string paisDescField;
        
        private string numeroDeCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal IngresosAcPrincipal {
            get {
                return this.ingresosAcPrincipalField;
            }
            set {
                this.ingresosAcPrincipalField = value;
                this.RaisePropertyChanged("IngresosAcPrincipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IngresosAcPrincipalSpecified {
            get {
                return this.ingresosAcPrincipalFieldSpecified;
            }
            set {
                this.ingresosAcPrincipalFieldSpecified = value;
                this.RaisePropertyChanged("IngresosAcPrincipalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal OtrosIngresos {
            get {
                return this.otrosIngresosField;
            }
            set {
                this.otrosIngresosField = value;
                this.RaisePropertyChanged("OtrosIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtrosIngresosSpecified {
            get {
                return this.otrosIngresosFieldSpecified;
            }
            set {
                this.otrosIngresosFieldSpecified = value;
                this.RaisePropertyChanged("OtrosIngresosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TotalIngresos {
            get {
                return this.totalIngresosField;
            }
            set {
                this.totalIngresosField = value;
                this.RaisePropertyChanged("TotalIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalIngresosSpecified {
            get {
                return this.totalIngresosFieldSpecified;
            }
            set {
                this.totalIngresosFieldSpecified = value;
                this.RaisePropertyChanged("TotalIngresosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TotalActivos {
            get {
                return this.totalActivosField;
            }
            set {
                this.totalActivosField = value;
                this.RaisePropertyChanged("TotalActivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalActivosSpecified {
            get {
                return this.totalActivosFieldSpecified;
            }
            set {
                this.totalActivosFieldSpecified = value;
                this.RaisePropertyChanged("TotalActivosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TotalPasivos {
            get {
                return this.totalPasivosField;
            }
            set {
                this.totalPasivosField = value;
                this.RaisePropertyChanged("TotalPasivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPasivosSpecified {
            get {
                return this.totalPasivosFieldSpecified;
            }
            set {
                this.totalPasivosFieldSpecified = value;
                this.RaisePropertyChanged("TotalPasivosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal GastosTotales {
            get {
                return this.gastosTotalesField;
            }
            set {
                this.gastosTotalesField = value;
                this.RaisePropertyChanged("GastosTotales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GastosTotalesSpecified {
            get {
                return this.gastosTotalesFieldSpecified;
            }
            set {
                this.gastosTotalesFieldSpecified = value;
                this.RaisePropertyChanged("GastosTotalesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OpMonedaExtranjera {
            get {
                return this.opMonedaExtranjeraField;
            }
            set {
                this.opMonedaExtranjeraField = value;
                this.RaisePropertyChanged("OpMonedaExtranjera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long TipoOperacionME {
            get {
                return this.tipoOperacionMEField;
            }
            set {
                this.tipoOperacionMEField = value;
                this.RaisePropertyChanged("TipoOperacionME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoOperacionMESpecified {
            get {
                return this.tipoOperacionMEFieldSpecified;
            }
            set {
                this.tipoOperacionMEFieldSpecified = value;
                this.RaisePropertyChanged("TipoOperacionMESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EntidadOPME {
            get {
                return this.entidadOPMEField;
            }
            set {
                this.entidadOPMEField = value;
                this.RaisePropertyChanged("EntidadOPME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OtraOperacionME {
            get {
                return this.otraOperacionMEField;
            }
            set {
                this.otraOperacionMEField = value;
                this.RaisePropertyChanged("OtraOperacionME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("Ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long TipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("TipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("TipoProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("Monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
                this.RaisePropertyChanged("MontoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string OtroTipoDeProducto {
            get {
                return this.otroTipoDeProductoField;
            }
            set {
                this.otroTipoDeProductoField = value;
                this.RaisePropertyChanged("OtroTipoDeProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CuentaBancaria {
            get {
                return this.cuentaBancariaField;
            }
            set {
                this.cuentaBancariaField = value;
                this.RaisePropertyChanged("CuentaBancaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PaisDesc {
            get {
                return this.paisDescField;
            }
            set {
                this.paisDescField = value;
                this.RaisePropertyChanged("PaisDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NumeroDeCuenta {
            get {
                return this.numeroDeCuentaField;
            }
            set {
                this.numeroDeCuentaField = value;
                this.RaisePropertyChanged("NumeroDeCuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteSarlaft : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nivelRiesgoField;
        
        private string certificacionField;
        
        private long origenFondosField;
        
        private bool origenFondosFieldSpecified;
        
        private string paisOrigenFondosDescField;
        
        private string detalleField;
        
        private long tipoContactoField;
        
        private bool tipoContactoFieldSpecified;
        
        private long lugarContactoField;
        
        private bool lugarContactoFieldSpecified;
        
        private string horaContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NivelRiesgo {
            get {
                return this.nivelRiesgoField;
            }
            set {
                this.nivelRiesgoField = value;
                this.RaisePropertyChanged("NivelRiesgo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Certificacion {
            get {
                return this.certificacionField;
            }
            set {
                this.certificacionField = value;
                this.RaisePropertyChanged("Certificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long OrigenFondos {
            get {
                return this.origenFondosField;
            }
            set {
                this.origenFondosField = value;
                this.RaisePropertyChanged("OrigenFondos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrigenFondosSpecified {
            get {
                return this.origenFondosFieldSpecified;
            }
            set {
                this.origenFondosFieldSpecified = value;
                this.RaisePropertyChanged("OrigenFondosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PaisOrigenFondosDesc {
            get {
                return this.paisOrigenFondosDescField;
            }
            set {
                this.paisOrigenFondosDescField = value;
                this.RaisePropertyChanged("PaisOrigenFondosDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("Detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long TipoContacto {
            get {
                return this.tipoContactoField;
            }
            set {
                this.tipoContactoField = value;
                this.RaisePropertyChanged("TipoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoContactoSpecified {
            get {
                return this.tipoContactoFieldSpecified;
            }
            set {
                this.tipoContactoFieldSpecified = value;
                this.RaisePropertyChanged("TipoContactoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long LugarContacto {
            get {
                return this.lugarContactoField;
            }
            set {
                this.lugarContactoField = value;
                this.RaisePropertyChanged("LugarContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LugarContactoSpecified {
            get {
                return this.lugarContactoFieldSpecified;
            }
            set {
                this.lugarContactoFieldSpecified = value;
                this.RaisePropertyChanged("LugarContactoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HoraContacto {
            get {
                return this.horaContactoField;
            }
            set {
                this.horaContactoField = value;
                this.RaisePropertyChanged("HoraContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteRef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWSDesmaterializadoRespClienteRefFamiliar familiarField;
        
        private ResponseWSDesmaterializadoRespClienteRefPersonal personalField;
        
        private ResponseWSDesmaterializadoRespClienteRefComercial comercialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWSDesmaterializadoRespClienteRefFamiliar Familiar {
            get {
                return this.familiarField;
            }
            set {
                this.familiarField = value;
                this.RaisePropertyChanged("Familiar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseWSDesmaterializadoRespClienteRefPersonal Personal {
            get {
                return this.personalField;
            }
            set {
                this.personalField = value;
                this.RaisePropertyChanged("Personal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseWSDesmaterializadoRespClienteRefComercial Comercial {
            get {
                return this.comercialField;
            }
            set {
                this.comercialField = value;
                this.RaisePropertyChanged("Comercial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteRefFamiliar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private decimal telefonoField;
        
        private bool telefonoFieldSpecified;
        
        private string ciudadDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("TelefonoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CiudadDesc {
            get {
                return this.ciudadDescField;
            }
            set {
                this.ciudadDescField = value;
                this.RaisePropertyChanged("CiudadDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteRefPersonal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private decimal telefonoField;
        
        private bool telefonoFieldSpecified;
        
        private string ciudadDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("TelefonoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CiudadDesc {
            get {
                return this.ciudadDescField;
            }
            set {
                this.ciudadDescField = value;
                this.RaisePropertyChanged("CiudadDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteRefComercial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private decimal telefonoField;
        
        private bool telefonoFieldSpecified;
        
        private string ciudadDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("TelefonoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CiudadDesc {
            get {
                return this.ciudadDescField;
            }
            set {
                this.ciudadDescField = value;
                this.RaisePropertyChanged("CiudadDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespClienteActivos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long activosNumeroVehiculosField;
        
        private bool activosNumeroVehiculosFieldSpecified;
        
        private long numeroBienesField;
        
        private bool numeroBienesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ActivosNumeroVehiculos {
            get {
                return this.activosNumeroVehiculosField;
            }
            set {
                this.activosNumeroVehiculosField = value;
                this.RaisePropertyChanged("ActivosNumeroVehiculos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivosNumeroVehiculosSpecified {
            get {
                return this.activosNumeroVehiculosFieldSpecified;
            }
            set {
                this.activosNumeroVehiculosFieldSpecified = value;
                this.RaisePropertyChanged("ActivosNumeroVehiculosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long NumeroBienes {
            get {
                return this.numeroBienesField;
            }
            set {
                this.numeroBienesField = value;
                this.RaisePropertyChanged("NumeroBienes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroBienesSpecified {
            get {
                return this.numeroBienesFieldSpecified;
            }
            set {
                this.numeroBienesFieldSpecified = value;
                this.RaisePropertyChanged("NumeroBienesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sio.experian.com/")]
    public partial class ResponseWSDesmaterializadoRespMasivas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroCampanaField;
        
        private bool numeroCampanaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long NumeroCampana {
            get {
                return this.numeroCampanaField;
            }
            set {
                this.numeroCampanaField = value;
                this.RaisePropertyChanged("NumeroCampana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroCampanaSpecified {
            get {
                return this.numeroCampanaFieldSpecified;
            }
            set {
                this.numeroCampanaFieldSpecified = value;
                this.RaisePropertyChanged("NumeroCampanaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Request", WrapperNamespace="http://sio.experian.com/", IsWrapped=true)]
    public partial class WSDesmaterializadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sio.experian.com/", Order=0)]
        public WebApplication.WSDesmaterializado.RequestWSDesmaterializadoReq WSDesmaterializadoReq;
        
        public WSDesmaterializadoRequest() {
        }
        
        public WSDesmaterializadoRequest(WebApplication.WSDesmaterializado.RequestWSDesmaterializadoReq WSDesmaterializadoReq) {
            this.WSDesmaterializadoReq = WSDesmaterializadoReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Response", WrapperNamespace="http://sio.experian.com/", IsWrapped=true)]
    public partial class WSDesmaterializadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sio.experian.com/", Order=0)]
        public WebApplication.WSDesmaterializado.ResponseWSDesmaterializadoResp WSDesmaterializadoResp;
        
        public WSDesmaterializadoResponse() {
        }
        
        public WSDesmaterializadoResponse(WebApplication.WSDesmaterializado.ResponseWSDesmaterializadoResp WSDesmaterializadoResp) {
            this.WSDesmaterializadoResp = WSDesmaterializadoResp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SIOTypeChannel : WebApplication.WSDesmaterializado.SIOType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SIOTypeClient : System.ServiceModel.ClientBase<WebApplication.WSDesmaterializado.SIOType>, WebApplication.WSDesmaterializado.SIOType {
        
        public SIOTypeClient() {
        }
        
        public SIOTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SIOTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIOTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIOTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.WSDesmaterializado.WSDesmaterializadoResponse WebApplication.WSDesmaterializado.SIOType.WSDesmaterializado(WebApplication.WSDesmaterializado.WSDesmaterializadoRequest request) {
            return base.Channel.WSDesmaterializado(request);
        }
        
        public WebApplication.WSDesmaterializado.ResponseWSDesmaterializadoResp WSDesmaterializado(WebApplication.WSDesmaterializado.RequestWSDesmaterializadoReq WSDesmaterializadoReq) {
            WebApplication.WSDesmaterializado.WSDesmaterializadoRequest inValue = new WebApplication.WSDesmaterializado.WSDesmaterializadoRequest();
            inValue.WSDesmaterializadoReq = WSDesmaterializadoReq;
            WebApplication.WSDesmaterializado.WSDesmaterializadoResponse retVal = ((WebApplication.WSDesmaterializado.SIOType)(this)).WSDesmaterializado(inValue);
            return retVal.WSDesmaterializadoResp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.WSDesmaterializado.WSDesmaterializadoResponse> WebApplication.WSDesmaterializado.SIOType.WSDesmaterializadoAsync(WebApplication.WSDesmaterializado.WSDesmaterializadoRequest request) {
            return base.Channel.WSDesmaterializadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.WSDesmaterializado.WSDesmaterializadoResponse> WSDesmaterializadoAsync(WebApplication.WSDesmaterializado.RequestWSDesmaterializadoReq WSDesmaterializadoReq) {
            WebApplication.WSDesmaterializado.WSDesmaterializadoRequest inValue = new WebApplication.WSDesmaterializado.WSDesmaterializadoRequest();
            inValue.WSDesmaterializadoReq = WSDesmaterializadoReq;
            return ((WebApplication.WSDesmaterializado.SIOType)(this)).WSDesmaterializadoAsync(inValue);
        }
    }
}
